PUNCTUATION = '!"#$%&()*+,-–./:;<=>?@[]^_`{|}~0123456789\\¿€♪„'
PUNC_TABLE = str.maketrans(dict.fromkeys(PUNCTUATION))
NORMALISATION = {'œ': 'oe'}
NORM_TABLE = str.maketrans(NORMALISATION)
IN_ENCODING = {
    'nl': 'UTF-8',
    'en': 'UTF-8',
    'es': 'UTF-8',
    'de': 'UTF-8',
    'fr': 'UTF-8',
    'pl': 'UTF-8',
    'it': 'UTF-8',
    'no': 'UTF-8',
    'pt': 'UTF-8',
    'sv': 'UTF-8',
    'ru': 'UTF-8'
    }
OUT_ENCODING = {
    'nl': 'ISO-8859-1',
    'en': 'UTF-8',
    'es': 'ISO-8859-1',
    'de': 'ISO-8859-1',
    'fr': 'ISO-8859-1',
    'pl': 'ISO-8859-2',
    'it': 'ISO-8859-1',
    'no': 'ISO-8859-1',
    'pt': 'ISO-8859-1',
    'sv': 'ISO-8859-1',
    'ru': 'ISO-8859-5'
    }
POS_TAGS = ["CC", 
            "CD", 
            "DT", 
            "EX", 
            "FW", 
            "IN", 
            "JJ", 
            "JJR", 
            "JJS", 
            "LS", 
            "MD", 
            "NN", 
            "NNS", 
            "NNP",
            "NNPS", 
            "PDT", 
            "POS", 
            "PRP", 
            "PRP$", 
            "RB", 
            "RBR", 
            "RBS", 
            "RP", 
            "SYM", 
            "TO", 
            "UH", 
            "VBD", 
            "VBG", 
            "VBN", 
            "VB", 
            "VBZ", 
            "WDT", 
            "WP", 
            "WP$", 
            "WRB", 
            "VBP"]
